### ISSUE TITLE
Connection refused issue when trying to check the exchange api [bug]

### ISSUE THREAD

**Issue by Nitu-coder** [edgexfoundry-holding/open-horizon-integration#31]
curl -u ${HZN_EXCHANGE_ROOT_USER_AUTH} ${HZN_EXCHANGE_URL}admin/version
curl: (7) Failed to connect to 107.108.87.226 port 3090: Connection refused

Can anybody help why is this issue??

**Comment by JoergWende** [comment]
double check if your HZN_EXCHANGE_URL still points to the correct ip address. I'm using DHCP so it might change after each reboot ....
J.

**Comment by JoergWende** [comment]
Not sure if this helps - depending on what steps you had been used before - this could be the start of research: 
a) if you are on a private network this will return the ip address of your router:
 export MY_IP=`curl -s httpbin.org/ip | jq -r .origin`
b) this will return your local hosts ip address:
export MY_IP=`ifconfig | egrep 'inet ' | awk '{ print $2 }' | egrep -v '^172.|^10.|^127.' | head -1`

**Comment by Nitu-coder** [comment]
EXCHANGE_AGBOT_NAME=agbot1 \
  EXCHANGE_AGBOT_TOKEN=agbot1pw \
  EXCHANGE_URL=http://107.108.87.226:3090/v1 \
  EXCHANGE_ROOT=root/root \
  EXCHANGE_PASSWORD=Horizon-Rul3s \
  EXCHANGE_ORGANIZATION=testorg \
  EXCHANGE_ADMIN_USERNAME=admin \
  EXCHANGE_ADMIN_PASSWORD=adminpw \
  && ./prime-exchange.sh

openhorizon/amd64_exchange-api:2.12.3 is the version of the container running for exchange api

is there an issue with the values set can you please let me know

**Comment by Nitu-coder** [comment]
Closing the issue with export MY_IP=ifconfig | egrep 'inet ' | awk '{ print $2 }' | egrep -v '^172.|^10.|^127.' | head -1

Issue resolved.
